name: env1
channels:
 - defaults
 - conda-forge
 - pytorch
dependencies:
 - python=3.7.9
 - joblib
 - jupytext
 - matplotlib
 - mypy
 - notebook
 - bert-tensorflow
 - tensorflow>=2.4.0
 - tensorflow-text
 - tf-models-official
 - gensim==4.0.0b0
 - praw
 - python-dotenv
 - numpy
 - pandas
 - pre-commit
 - pylint
 - pytorch
 - scikit-learn
 - scipy
 - statsmodels
 - torchvision
 - r-ggplot2
 - virtualenv
 - pip
 - python-dateutil