name: env1
channels:
 - defaults
 - conda-forge
 - pytorch
dependencies:
 - python=3.7.9
 - black
 - fbprophet
 - joblib
 - jupytext
 - matplotlib
 - mypy
 - networkx
 - notebook
 - nltk
 - bert-tensorflow
 - tensorflow>=2.4.0
 - tensorflow-text
 - tf-models-official
 - numpy
 - pandas
 - pre-commit
 - pylint
 - pytorch
 - scikit-learn
 - scipy
 - statsmodels
 - torchvision
 - r-ggplot2
 - virtualenv
 - pip
 - yellowbrick
 - gensim==4.0.0b0
 - praw
 - inflect
 - dotenv
 - python-dotenv
 - lxml
 - python-dateutil