name: conda_env1
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3.7.9
 - jupytext
 - matplotlib
 - mypy
 - notebook
 - joblib
 - bert-tensorflow
 - tensorflow>=2.4.0
 - tensorflow-text
 - tf-models-official
 - gensim==4.0.0b0
 - praw
 - python-dotenv
 - numpy
 - pandas
 - pylint
 - scikit-learn
 - scipy
 - virtualenv
 - pip
 - python-dateutil