name: nlpenv02
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3.7.9
 - joblib
 - tokenizers>=0.10.1
 - transformers>=4.4.2
 - praw
 - python-dotenv
 - numpy
 - pandas
 - scikit-learn
 - scipy
 - virtualenv
 - python-dateutil
 - pip
 - pip:
   - -r file:requirements.txt